name: Deploy to cPanel

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2 # Updated to v2
      with:
        node-version: '20' # Updated to a more recent version

    - name: Build React App
      run: |
        npm install
        npm run build

    - name: Zip Build Directory
      run: zip -r build.zip dist/ 

    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@4.2.0 
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: dist/ 
